FROM rustlang/rust:nightly-buster@sha256:ca626ba169b1b720fcdad3c9ebdba1a97ed4cc0cc2ad53f70c456ca4ccd96537 as builder
WORKDIR /usr/src/mainapp
COPY . .
RUN cargo build --release

FROM debian:buster-slim
WORKDIR /usr/app
COPY --from=builder /usr/src/mainapp/target/release/reader /usr/app/
CMD ["./reader"]
