apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: hy-kube-project
  name: backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-dep
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50