apiVersion: batch/v1
kind: CronJob
metadata:
  name: randomtask
  namespace: hy-kube-project
spec:
  schedule: "0 8 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: randomtask
            image: IMAGE_RANDOMTASK
            resources:
              limits:
                cpu: "50m"
                memory: "50Mi"
            imagePullPolicy: Always
            env:
              - name: API_URL
                value: http://backend-svc:3456/api
          restartPolicy: Never