apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hy-kube-project
  name: backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
        - name: project-volume
          persistentVolumeClaim:
            claimName: project-claim
      containers:
        - name: hy-kube-backend
          image: IMAGE_BACKEND
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "100m"
              memory: "50Mi"
          volumeMounts:
            - name: project-volume
              mountPath: /usr/app/files
          envFrom:
          - configMapRef:
              name: backend-config
          - configMapRef:
              name: project-db-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: PASSWORD
            - name: POSTGRES_IP
              valueFrom:
                secretKeyRef:
                  name: postgres-ip
                  key: POSTGRES_IP
            - name: DATABASE_URL
              value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_IP)/$(POSTGRES_DB)?sslmode=disable
            - name: ROCKET_DATABASES
              value: '{projectdb={url="$(DATABASE_URL)"}}'