apiVersion: apps/v1
kind: Deployment
metadata:
  name: hy-kube-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hy-kube-backend
  template:
    metadata:
      labels:
        app: hy-kube-backend
    spec:
      containers:
        - name: hy-kube-backend
          image: tkasu/hy-kube-backend:ex1.06
          env:
            - name: ROCKET_PORT
              value: "3000"