apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hy-kube-project
  name: hy-kube-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hy-kube-backend
  template:
    metadata:
      labels:
        app: hy-kube-backend
    spec:
      volumes:
        - name: project-volume
          persistentVolumeClaim:
            claimName: hy-kube-project-claim
      containers:
        - name: hy-kube-backend
          image: tkasu/hy-kube-backend:ex2.02
          imagePullPolicy: Always
          volumeMounts:
            - name: project-volume
              mountPath: /usr/app/files
          env:
            - name: ROCKET_PORT
              value: "3000"
            - name: IMAGE_CACHE_PATH
              value: /usr/app/files/img.jpg
            - name: IMAGE_STATE_PATH
              value: /usr/app/files/img_state.json
            - name: IMAGE_UPDATE_INTERVAL
              value: "86400" # Seconds in a day