apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: hy-kube-project
  name: project-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.1Gi