apiVersion: v1
kind: Service
metadata:
  namespace: hy-kube-project
  name: backend-svc
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 3456
      targetPort: 3000