apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mainapp
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: hy-kube-pingpong
          image: tkasu/hy-kube-pingpong:ex3.02
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: pingpong-config
          - configMapRef:
              name: pingpong-postgres-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: PASSWORD
            - name: DATABASE_URL
              value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@pingpong-db/$(POSTGRES_DB)
            - name: ROCKET_DATABASES
              value: '{pingpongdb={url="$(DATABASE_URL)"}}'
