apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mainapp
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: hy-kube-pingpong
          image: tkasu/hy-kube-pingpong:ex2.03
          imagePullPolicy: Always
          env:
            - name: ROCKET_PORT
              value: "3000"
