apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: mainapp
  name: postgres-pv
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi 
  volumeMode: Filesystem 
  accessModes:
  - ReadWriteOnce
  local:
    path: /tmp/kube_pg
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3d-k3s-default-agent-0