apiVersion: v1
kind: Service
metadata:
  namespace: mainapp
  name: hy-kube-pingpong-svc
spec:
  type: ClusterIP
  selector:
    app: hy-kube-pingpong
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000