apiVersion: v1
kind: Service
metadata:
  namespace: mainapp
  name: pingpong-svc
spec:
  type: ClusterIP
  selector:
    app: pingpong
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000