apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mainapp
  name: hy-kube-mainapp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hy-kube-mainapp
  template:
    metadata:
      labels:
        app: hy-kube-mainapp
    spec:
      volumes:
        - name: timestamps-volume
          emptyDir: {}
      containers:
        - name: hy-kube-mainapp-reader
          image: tkasu/hy-kube-mainapp-reader:ex2.08
          imagePullPolicy: Always
          volumeMounts:
            - name: timestamps-volume
              mountPath: /usr/app/files
          envFrom:
            - configMapRef:
                name: mainapp-configmap
        - name: hy-kube-mainapp-writer
          image: tkasu/hy-kube-mainapp-writer:ex2.08
          imagePullPolicy: Always
          volumeMounts:
            - name: timestamps-volume
              mountPath: /usr/app/files
          envFrom:
            - configMapRef:
                name: mainapp-configmap
