apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mainapp
  name: hy-kube-mainapp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hy-kube-mainapp
  template:
    metadata:
      labels:
        app: hy-kube-mainapp
    spec:
      volumes:
        - name: timestamps-volume
          emptyDir: {}
      containers:
        - name: hy-kube-mainapp-reader
          image: tkasu/hy-kube-mainapp-reader:ex2.03
          imagePullPolicy: Always
          volumeMounts:
            - name: timestamps-volume
              mountPath: /usr/app/files
          env:
            - name: ROCKET_PORT
              value: "3000"
            - name: MAINAPP_FILE_PATH
              value: /usr/app/files/timestamps.txt
            - name: MAINAPP_WRITER_UPDATE_FREQ
              value: http://hy-kube-pingpong-svc
        - name: hy-kube-mainapp-writer
          image: tkasu/hy-kube-mainapp-writer:ex2.03
          imagePullPolicy: Always
          volumeMounts:
            - name: timestamps-volume
              mountPath: /usr/app/files
          env:
            - name: MAINAPP_FILE_PATH
              value: /usr/app/files/timestamps.txt
