apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mainapp
  name: mainapp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mainapp
  template:
    metadata:
      labels:
        app: mainapp
    spec:
      volumes:
        - name: timestamps-volume
          emptyDir: {}
      containers:
        - name: mainapp-reader
          image: tkasu/hy-kube-mainapp-reader:ex3.02
          resources:
            limits:
              cpu: "10m"
              memory: "20Mi"
          imagePullPolicy: Always
          volumeMounts:
            - name: timestamps-volume
              mountPath: /usr/app/files
          envFrom:
            - configMapRef:
                name: mainapp-configmap
        - name: mainapp-writer
          image: tkasu/hy-kube-mainapp-writer:ex3.02
          resources:
            limits:
              cpu: "10m"
              memory: "20Mi"
          imagePullPolicy: Always
          volumeMounts:
            - name: timestamps-volume
              mountPath: /usr/app/files
          envFrom:
            - configMapRef:
                name: mainapp-configmap
