apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hy-kube-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: hy-kube-mainapp-svc
              servicePort: 2345