apiVersion: v1
kind: Service
metadata:
  namespace: mainapp
  name: mainapp-svc
spec:
  type: NodePort
  selector:
    app: mainapp
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000