apiVersion: v1
kind: Secret
metadata:
    name: postgres-password
    namespace: hy-kube-project
data:
    PASSWORD: ENC[AES256_GCM,data:3F7yXkWTpAXTpBNyTQJ0G/CTnvCRxr2Q3DaCiDrfYa6ZVufCwgY/zQ==,iv:h8vzoVkGzyFbZfffOy3lKflbJmz8tReBIAk5sdu/oVY=,tag:La5tktSVVz2T6njU/FwiGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age162unsh9g6c94es64yqljgtxc9j4z395crnz7cvqyxhm3shs8qusqnqynr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVGROZkszSXhXbXFrU1ZM
            Qlh6NjdITmxHbUxCWE5lWU1XRnJuRk5rbGk0Ck5RWG1SK3MzUi9EL1Vnd3pScVpR
            b05hNFJXQnZHVkJTK29HZTlWWlpaL2MKLS0tIDhmNmhlQ29pS25XYkZLdXZxdHRN
            SE91V1o1WUc1UkxwMWJyVk9mdFVqWmcKAv5dBDIyqhI1kxrcLpRrYIpZ4Vm6BhEu
            FktwME43eLNqw1e5Xw/cO1jql5ZNxjOVZSqpe8+lY2snYYX13nl0Mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-12T18:12:48Z"
    mac: ENC[AES256_GCM,data:f9XgyOuXW21GgA9u5/ION05k6KMe03Px2qfE/sm5j3ZqfIdXyX6rGRzG9cdCEKJ+SupLnEIesa4bK3xYalonO9YwwgWizUqeWn0H/3PGmEP9d75afvcYAkISJCpCrDX8vquLaLA72PO+Mci+jvrVdqJqIaz5v7ILt0b6FwyK5n0=,iv:phkwYVT2+00cwoUs+bxe+tZtm1jIhbReh9/nqmy159E=,tag:3Yjii0dqXPEh5DBZzORtaw==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
