apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backend/
  - frontend/
namespace: hy-kube-project
images:
  - name: IMAGE_FRONTEND
    newName: tkasu/hy-kube-frontend
  - name: IMAGE_BACKEND
    newName: tkasu/hy-kube-backend
  - name: IMAGE_RANDOMTASK
    newName: tkasu/hy-kube-backend-randomtask