apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backend/
  - frontend/
namespace: hy-kube-project
images:
  - name: IMAGE_FRONTEND
    newName: europe-north1-docker.pkg.dev/dwk-gke-354607/dwk-gke-354607-default/hy-kube-frontend
  - name: IMAGE_BACKEND
    newName: europe-north1-docker.pkg.dev/dwk-gke-354607/dwk-gke-354607-default/hy-kube-backend
  - name: IMAGE_BACKEND_IMAGESYNC
    newName: europe-north1-docker.pkg.dev/dwk-gke-354607/dwk-gke-354607-default/hy-kube-backend-imagesync
  - name: IMAGE_RANDOMTASK
    newName: europe-north1-docker.pkg.dev/dwk-gke-354607/dwk-gke-354607-default/hy-kube-randomtask