apiVersion: v1
kind: Secret
metadata:
    name: postgres-password
    namespace: mainapp
data:
    #ENC[AES256_GCM,data:HkgZY1fRqYExMT+kPirsGzdLiGlXVI2XKM5LFxGF+g==,iv:eg6dRuOOmUwFA00UZXwERBAjMQ/lbKULSl84VeH2XMM=,tag:hAEPYO7mLJcw+k2/p1+fHA==,type:comment]
    PASSWORD: ENC[AES256_GCM,data:VaaS/wc7bgUq4k1mOConB95QoGxQIn1dcss+VQNlyBG+sQbG10xrYw==,iv:YjonIZ7cXLMaMhBRwhnhMx3ddzK3lbxVvO1N9JhNxiY=,tag:nT013cSDShdgqWpuc9FV3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age162unsh9g6c94es64yqljgtxc9j4z395crnz7cvqyxhm3shs8qusqnqynr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWU5rTzNkQ0trNVRvSCtO
            QVJETG8zMXRxSFRHRWMxVUlIUWI1TG5rUlFJCiswREVBbHJCRGZnQ0dsS1Z5OVkw
            U0hUNFBBY2hyd3ZPSWpuS3RrY2ZmaGsKLS0tIExNbUNadDA4bXVkZ1QzNG5hWStW
            L0ZFc2VCUDRYaHFEdmxRcmNNZnpGWHcKv5chf8m6s0SDFozVw+2zLpYXeoA78VgE
            nzX/mi2W7k+1vF+boD5Ig2qC/91R/tcMl6SZgT45Jmjj5NKngwluTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-28T10:23:57Z"
    mac: ENC[AES256_GCM,data:u4z6XgXqAYUzPpqYbXSSFWIFL3ySBhMyi23KOPP6dh+8oco+9+7zQMlbPwG8uja2+5osYz7E7GTIX3UN6xaPnHOtvdAskQ3ZeIGhYLcoYfDJLTv8N+aSPkDa5zGZDdaXWlzyERLjn3x2TgwduWyosm3LWDAZnMxwySD+goDydxY=,iv:ov1aeEsjCfb00BCjgQvlwzbtDt7pbyiZubnUpjDZzeI=,tag:NoSDwBlsMQR6R6cTzBV6dA==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
