apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dep
  namespace: hy-kube-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes:
        - name: project-volume
          persistentVolumeClaim:
            claimName: project-claim
      containers:
        - name: hy-kube-frontend
          image: tkasu/hy-kube-frontend:ex3.03
          imagePullPolicy: Always
