apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: hy-kube-project
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      protocol: TCP
      port: 2345
      targetPort: 80