apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hy-kube-mainapp-pingpong-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi