FROM rust:1.61.0-buster as builder
WORKDIR /usr/src/backend
COPY . .
RUN cargo build --release

FROM debian:buster-slim
WORKDIR /usr/app/backend
COPY --from=builder /usr/src/backend/target/release/randomtask .
RUN apt-get update && apt-get install -y libssl-dev ca-certificates
CMD ["./randomtask"]