name: CI&CD

on:
  push:
    tags:
      - ex**

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-push-pingpong:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pingpong

    steps:
    - uses: actions/checkout@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: tkasu/hy-kube-pingpong

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./pingpong
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  build-and-push-mainapp-writer:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mainapp

    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: tkasu/hy-kube-mainapp-writer

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./mainapp
        file: ./mainapp/Dockerfile.writer
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  build-and-push-mainapp-reader:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mainapp

    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: tkasu/hy-kube-mainapp-reader

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./mainapp
        file: ./mainapp/Dockerfile.reader
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
